services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: link_tracker
    volumes:
      - ./log-directory:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d link_tracker
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - backend

  liquibase-migrations:
    container_name: migrations
    image: liquibase/liquibase:4.29
    depends_on:
      - postgresql
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/link_tracker
      - --username=postgres
      - --password=123
      - update
    volumes:
      - ./migrations:/changesets
    networks:
      - backend

volumes:
  db_data: {}

networks:
  backend: {}
