app:
  telegram-token: ${APP_TELEGRAM_TOKEN} # env variable
  telegram-name: ${APP_TELEGRAM_NAME}
  user-events:
    topic: notifications-from-resources

scrapper:
  base-url: "http://localhost:8081"

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092
    consumer.properties:
      enable.auto.commit: false
      auto.offset.reset: earliest
      isolation.level: read_committed
      fetch.min.bytes: 1024
      fetch.max.bytes: 1048576
      fetch.max.wait.ms: 10000
      max.poll.interval.ms: 10000
      max.poll.records: 10
    cloud.zookeeper:
      config.enabled: false
      connect-string: localhost:2181

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  structured:
    format:
      console: ecs
