app:
  telegram-token: ${APP_TELEGRAM_TOKEN} # env variable
  telegram-name: ${APP_TELEGRAM_NAME}

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
