name: Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: edu-self-hosted
    container:
      image: maven:3-eclipse-temurin-24
    timeout-minutes: 15
    name: Build
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: maven build
        run: mvn verify

      - id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        if: ( github.event_name != 'workflow_dispatch' )
        with:
          paths: ${{ github.workspace }}/report/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 30
          title: Code Coverage
          update-comment: true

  linter:
    name: linter
    runs-on: edu-self-hosted
    container:
      image: maven:3-eclipse-temurin-24
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - run: mvn compile -am spotless:check modernizer:modernizer spotbugs:check pmd:check pmd:cpd-check
